name: 'sync cowllector'
on:
  schedule:
    - cron: '0 */4 * * *' # At the start of every 4th hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y openssh-client git nodejs
      - run: npm install --global yarn
      - run: |
          git config --global user.email "beefy.team@pm.me"
          git config --global user.name "beefybot"
      - name: Setup key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.BEEFY_BOT_SSH_PK }}
      - name: Sync Cowllector
        run: |
          git clone git@github.com:beefyfinance/beefy-cowllector.git cowllector
          cd cowllector
          yarn install
          yarn lost
          yarn sync
          yarn updateGasLimit
          git add .
          git commit -m "sync"
          git push origin master
          git checkout prod
          git merge master
          git push origin prod
          echo "done"
